### ISSUE TITLE
SideNav: Splitpanel Divider still shows on top of menu

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/servoy-extra-components#1]
When the menu slides in, it covers the split panel, but the divider is still on top

If we send the component to the front, then the buttons in the form in splitpane are not clickable, they are covered by the menu component

**Comment by paronne** [comment]
Fixed splitpane divider on top of the sidenav.

In anchored form if the sidenav menu is on top (greater z-index) then other elements or tabs, even when the sidenav menu is collapsed, the content below the sidenav is not clickable.

If you want to place content below the sidenav component in an anchored form, make sure that the sidenav menu is positioned below the other elements in the designed form.
