### ISSUE TITLE
Adding Script to onMenuItemSelected blocks visuals

### ISSUE THREAD

**Issue by clickdigital** [Servoy/servoy-extra-components#14]
The SideBar component has a style which highlights the selected menu when clicked. IF you add a controller script to onMenuItemSelected this behaviour is removed, if the script is disabled the feature returns.

**Comment by paronne** [comment]
The onMenuItemSelected event can prevent the selection of the item if does not return true.

**Comment by clickdigital** [comment]
Thank you, this sorted the problem, I did not see it in the docs if its not there its probably worth adding.

**Comment by paronne** [comment]
Added a fix that the selection is prevented only if the onMenuItemSelected returns false
