### ISSUE TITLE
servoy-extra-components/treeview/ refresh problem

### ISSUE THREAD

**Issue by juanetec** [Servoy/servoy-extra-components#15]
Hi, 
using treeview servoy-extra-components it doesn't refresh when you change the dataset from de treeview, even using the treeview.refresh(true).
I have attach es and example with that problem. (CASE A).
Pressing the button LoadDatasetB on the example the treeview does not change.

Thanks.
Juan Ramírez

[example.zip](https://github.com/Servoy/servoy-extra-components/files/810790/example.zip)

**Comment by gboros** [comment]
fixed, you even don't need to call refresh, as soon as you set the new dataset, it reloads

**Comment by juanetec** [comment]
I delete servoy extra components in my example application and download 
it again, but it doesn't work.
I saw that the change was in the treeview.js file.
But I notice that it doesn't download with the web packages manager.
I have done manually, but with the example I have send, it doesn't work 
as well.


Un Saludo


Juan Ramírez

Mv. +34 678 535 170
Tlf +34 928 49 28 45

www.etecsoft.com <https://www.etecsoft.com:8443>

Advertencia / Confidentiality Notice

Este envío es confidencial y está destinado únicamente a la persona a la 
que ha sido enviado. Puede contener información privada y confidencial. 
Si usted no es el destinatario al que ha sido remitida, no puede 
copiarla, distribuirla ni emprender con ella ningún tipo de acción. Si 
cree que lo ha recibido por error, por favor, notifíquelo al remitente.

/This transmission is confidential and intended solely for the person to 
whom it is addressed. It may contain privileged and confidential 
information. If you are not the intended recipient, you should not copy, 
distribute or take any action in reliance on it. If you believe that you 
have received this transmission in error, please notify the sender./

Etec Programación, S.L.

**Comment by gboros** [comment]
are you sure it is running with the modified tree view.js? can you check it in Chrome with developer tools?

**Comment by juanetec** [comment]
I see is de old one.











Un Saludo


Juan Ramírez

Mv. +34 678 535 170
Tlf +34 928 49 28 45

www.etecsoft.com <https://www.etecsoft.com:8443>

Advertencia / Confidentiality Notice

Este envío es confidencial y está destinado únicamente a la persona a la 
que ha sido enviado. Puede contener información privada y confidencial. 
Si usted no es el destinatario al que ha sido remitida, no puede 
copiarla, distribuirla ni emprender con ella ningún tipo de acción. Si 
cree que lo ha recibido por error, por favor, notifíquelo al remitente.

/This transmission is confidential and intended solely for the person to 
whom it is addressed. It may contain privileged and confidential 
information. If you are not the intended recipient, you should not copy, 
distribute or take any action in reliance on it. If you believe that you 
have received this transmission in error, please notify the sender./

Etec Programación, S.L.

**Comment by juanetec** [comment]
I change to the firefox browser there is the new version but it dosen't 
work.
Probably with the chrome is in cache.

Un Saludo


Juan Ramírez

Mv. +34 678 535 170
Tlf +34 928 49 28 45

www.etecsoft.com <https://www.etecsoft.com:8443>

Advertencia / Confidentiality Notice

Este envío es confidencial y está destinado únicamente a la persona a la 
que ha sido enviado. Puede contener información privada y confidencial. 
Si usted no es el destinatario al que ha sido remitida, no puede 
copiarla, distribuirla ni emprender con ella ningún tipo de acción. Si 
cree que lo ha recibido por error, por favor, notifíquelo al remitente.

/This transmission is confidential and intended solely for the person to 
whom it is addressed. It may contain privileged and confidential 
information. If you are not the intended recipient, you should not copy, 
distribute or take any action in reliance on it. If you believe that you 
have received this transmission in error, please notify the sender./

Etec Programación, S.L.

**Comment by gboros** [comment]
om my side, the tree on the left from your sample does update, both on chrome & firefox;
what if remove the refresh calls from the button action when you change the dataset ? is then
different ? if you set a breakpoint in the treeview.js in the watch on 'model.jsDataSet' does it
get hit ? is the reload called inisde that watch ?

**Comment by juanetec** [comment]
Yes now is working thanks.
Probably was the caché.




Un Saludo


Juan Ramírez

Mv. +34 678 535 170
Tlf +34 928 49 28 45

www.etecsoft.com <https://www.etecsoft.com:8443>

Advertencia / Confidentiality Notice

Este envío es confidencial y está destinado únicamente a la persona a la 
que ha sido enviado. Puede contener información privada y confidencial. 
Si usted no es el destinatario al que ha sido remitida, no puede 
copiarla, distribuirla ni emprender con ella ningún tipo de acción. Si 
cree que lo ha recibido por error, por favor, notifíquelo al remitente.

/This transmission is confidential and intended solely for the person to 
whom it is addressed. It may contain privileged and confidential 
information. If you are not the intended recipient, you should not copy, 
distribute or take any action in reliance on it. If you believe that you 
have received this transmission in error, please notify the sender./

Etec Programación, S.L.
