### ISSUE TITLE
Table Component - Expose the Valuelist

### ISSUE THREAD

**Issue by issBrenda** [Servoy/servoy-extra-components#18]
Can the valuelist be exposed to table.column?

Something like:

getValueListName()
setValueList(string)

Otherwise, we have no way to add a new column to the Table that has a valuelist.

**Comment by seanthomasdevlin** [comment]
related to [SVY-10931](https://support.servoy.com/browse/SVY-10931)

**Comment by jcompagner** [comment]
problem is that column.valuelist gives back the dataset..
We will fix that if column = {xxx=yyy, valuelist=test} will start working 
But this won't fix the problem of getting the valuelist name, having api like that is not so nice, and we don't current support really api on those types, so we can't add that.

The only fix for that is now using the solution model to get it.

**Comment by lvostinar** [comment]
Fixed this in Servoy code, see related issue in Jira. Should use:
elements.table_1.columns.push({'dataprovider':'shipvia','valuelist':'test','headerText':'newone'})
to add new column.

**Comment by costescuandrei** [comment]
Some more fixes were needed for similar scenarios. See https://support.servoy.com/browse/SVY-10931 for more info. That is why I reopened it.

**Comment by costescuandrei** [comment]
Fixed for 8.2.

**Comment by costescuandrei** [comment]
So now for a valuelist property - reading it will give the valuelist's name.

When you set a value to it:

- if it is already a custom valuelist, you can give a Dataset and the items will be changed only for that component's valuelist
- you can give a valuelist name
