### ISSUE TITLE
Error when sorting paginated table

### ISSUE THREAD

**Issue by pruhsert** [Servoy/servoy-extra-components#21]
I have a larger table with pagination. Sitting on page 1 I can sort whatever I like. When I navigate to the next page and want to sort differently, I end up with an empty table and this error:

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at updateRenderedRows (table.js:1556)
    at generateTemplate (table.js:1957)
    at table.js:577

Sample solution attached. To reproduce, open solution and sort by Quantity. The navigate to page 2 and sort by Quantity the other direction.

[key_components.zip](https://github.com/Servoy/servoy-extra-components/files/986923/key_components.zip)

**Comment by costescuandrei** [comment]
This is already fixed right?

**Comment by gboros** [comment]
the commit that fixed this issue : https://github.com/Servoy/servoy-extra-components/commit/5cbbd66abe00ba735489ebb5cd583a57f2443778
