### ISSUE TITLE
Image in Table

### ISSUE THREAD

**Issue by vweimer** [Servoy/servoy-extra-components#23]
Hi,
is there any way to add an image (by a calculation) to a table as a column. Somehow it looks like the return type media for a calculation does not work as expected and adding html tags as return value to the calculation end up in html encoding (< is encoded to &lt).

**Comment by costescuandrei** [comment]
If you use a regular, unrelated media column or calculation it works right?

I know there is a problem with related columns and MEDIA type. There is a case for that, It might be the same problem for your if you are trying to use a related calculation.

**Comment by costescuandrei** [comment]
This is similar to https://github.com/Servoy/servoy-extra-components/issues/17.

**Comment by jcompagner** [comment]
the problem with this could potentially be the html sanitize that is done by angular
So it could be that you need to explicitly say that full html is allowed
