### ISSUE TITLE
Table component: can scroll way beyond the last record

### ISSUE THREAD

**Issue by p-bakker** [Servoy/servoy-extra-components#24]
Environment: Servoy 8.2b1

All records in teh foundset are loaded, but the component allows scrolling beyond that

See attached screenshots

![table display](https://cloud.githubusercontent.com/assets/4981149/26817386/a24a8dc0-4a96-11e7-9efa-6cd51c234157.png)
![markup](https://cloud.githubusercontent.com/assets/4981149/26817387/a3a79514-4a96-11e7-96fc-6ac125bf120e.png)

**Comment by costescuandrei** [comment]
Any specific performanceSettings (in properties view) or are you just using defaults?
Any exceptions in browser console when this happens?

**Comment by p-bakker** [comment]
Nevermind...

Due to your questions I decided to test the form containing the grid as my main form: problem solved. 

The issue is that I'm running my form containing the table inside a custom webcomponent, similar to a form in a tab in a tabpanel. There's a bug however in Servoy 8.2b1 if you do that: the component is not allowed to talk back to the server and all kind of things go wrong. 

This issue seems to be one of them.

Will create a new issue for that once I have a small reproducible sample
