### ISSUE TITLE
Side Nav scrolling no longer working in 1.1.4

### ISSUE THREAD

**Issue by iangus** [Servoy/servoy-extra-components#26]
Updating from version 1.1.3 to 1.1.4 introduces an issue where the side nav doesn't become scrollable when it's menu items expand below the screen.

1.1.3:___________________________________1.1.4:
![seperatelyscrollable](https://user-images.githubusercontent.com/16198817/27188315-c27ba88c-51bb-11e7-8c35-8806dd8f52a2.png)  ![notscrollable](https://user-images.githubusercontent.com/16198817/27188328-cdc280ee-51bb-11e7-9f19-8556000cfebf.png)

**Comment by meraedit** [comment]
fixed by https://support.servoy.com/browse/SVY-11249
