### ISSUE TITLE
File Upload should provide mime type and file name

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/servoy-extra-components#28]
linked to [SVY-11264
](https://support.servoy.com/browse/SVY-11264)

Perhaps this is best implemented with a new callback, possibly replacing onDataChange

/**
  \* @param {Array<byte>} bytes
  \* @param {String} fileName
  \* @param {String} mimeType
  */
onFileUpload(bytes, fileName, mimeType){
    
}

**Comment by costescuandrei** [comment]
A comment on SVY-11264 describes how this can already be done.
Should we still add a new callback?
