### ISSUE TITLE
Table Component Selected Row not updating

### ISSUE THREAD

**Issue by issBrenda** [Servoy/servoy-extra-components#30]
We are using the Table Component, and on 2 of our screens, it is not updating the Selected Row Highlight.  Please see the screen capture below.  Link is provided.

The Foundset selected Record is updated, but the highlighted row is not.

Servoy Version: 8.1.4  - build 3035

Servoy Extra Components 1.1.4

https://www.screencast.com/t/THt1pwil

**Comment by seanthomasdevlin** [comment]
Linking this to issue in Servoy Jira
https://support.servoy.com/browse/SVY-11585

**Comment by costescuandrei** [comment]
Case https://support.servoy.com/browse/SVY-11585 is closed as awaiting input.
I am closing this one as well; if new info on how this can be reproduced appears, please reopen both this Github issue and the JIRA case.
