### ISSUE TITLE
TABLE component responsiveDynamicHeight does not work

### ISSUE THREAD

**Issue by juanetec** [Servoy/servoy-extra-components#36]
Hi,
starting using the TABLE component and when I set to true the responsiveDynamicHeight this property does not work or I don't understand how to use it. 
What I need is not to fix the height, the height have to resize their self.

Thanks.
Juan Ramírez

**Comment by paronne** [comment]
Hi Juan, 

the responsiveDynamicHeight is applicable only if the table is used in responsiveForms. Still the responsiveHeight property will be used as maxHeight; 
it basically allow the table to use only the height necessary up to max responsiveHeight (then will show scrollbar); 

For example if you have a responsiveHeight of 500px but your table shows only 2 records, when responsiveDynamicHeight is true the table will take only few pixels in height (the header + the 2 rows). The table will grow up to the max 500px, then if more rows are added it will show a scrollbar.

Regards,
Paolo
