### ISSUE TITLE
select2tokenizer jumps to top selection

### ISSUE THREAD

**Issue by iangus** [Servoy/servoy-extra-components#4]
After making a selection in the dropdown the highlighted selection jumps back up to the first selected element.

**Comment by paronne** [comment]
This is a behavior of the underlying library Select2.
This issue has been already reported here https://github.com/select2/select2/issues/4417

**Comment by iangus** [comment]
Removing the method call highlightFirstItem from container.on('select') line 1038 of the full js file or b.on("select") in the minified file fixes the issue. Is there any reason to keep this method call. I don't understand the purpose of highlighting the first selected element after a selection is made. Thoughts on this?

**Comment by jcompagner** [comment]
thats a discussion for the issue paolo is pointing out in the comment above.

**Comment by costichiulan** [comment]
Applied patch https://github.com/select2/select2/pull/5150/files/3e74040a98da154ee5a647c9891ccd4c2713a499
