### ISSUE TITLE
Collapsible doesn't show contained table view form on first load (need refresh)

### ISSUE THREAD

**Issue by tuanway** [Servoy/servoy-extra-components#43]
![collapse first load](https://user-images.githubusercontent.com/7150474/37998012-97f92c76-31e2-11e8-8a61-ea3f9b5d9fc7.PNG)

On first load it doesn't show the form.  We need to refresh manually using browser for it to appear.

Tested on Servoy Version 8.2.3 

Attached a sample solution
[collapseTest.zip](https://github.com/Servoy/servoy-extra-components/files/1853985/collapseTest.zip)

**Comment by lvostinar** [comment]
Fixed, see https://support.servoy.com/browse/SVY-12303
