### ISSUE TITLE
Select2Tokenizer does not work on IE11

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/servoy-extra-components#46]
Having looked at the code this issue is also related to #45 as both components use the Javascript native Promise which is not supported in IE11. There are documented workarounds for this that allow promise type functionality to work with IE11 and whilst this is still a supported browser by Microsoft then I think the Servoy components should also support that browser.

**Comment by lvostinar** [comment]
Is fixed now, see https://support.servoy.com/browse/SVY-12455
