### ISSUE TITLE
Cannot select text in Table component

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/servoy-extra-components#47]
There seems to be no way to select and copy text that is displayed in the table component. Any idea how we might enable this?

**Comment by pruhsert** [comment]
We inherit that from a css, that you could override. See this

.tablewrapper tbody td div {
	-webkit-user-select: none; /* Chrome all / Safari all */
	-moz-user-select: none; /* Firefox all */
	-ms-user-select: none; /* IE 10+ */
	/* No support for these yet, use at own risk */
	-o-user-select: none;
	user-select: none;
}

If you add this to your own css and set it to initial for example, it should work
