### ISSUE TITLE
Table does not empty when foudset becomes 0 records from a foundset.loadRecords(anotherFoundset) when paginated

### ISSUE THREAD

**Issue by jorgesedavi** [Servoy/servoy-extra-components#48]
When a table is using the form foundset, and it becomes 0 records by a foundset.loadRecords(anotherFoundset), the extra-table does not empty if it is paginated and the user is placed on a page different than first one. A workaround could be achieved by adding this:
if(foundset.getSize() === 0)
{
foundset.loadRecords();
foundset.clear();
}

Tested on latest servoy-extra-components package and on Servoy 8.3 and 8.3.1RC1.

I attach a sample solution on zip
[test_ExtraTable.zip](https://github.com/Servoy/servoy-extra-components/files/2196872/test_ExtraTable.zip)
. Reported on Jira on https://support.servoy.com/browse/SVY-12618

**Comment by costescuandrei** [comment]
Fixed in Servoy 8.3.2.
