### ISSUE TITLE
Table component: rowStyleClassDataProvider inconsequent behaviour on consecutive pages

### ISSUE THREAD

**Issue by og1** [Servoy/servoy-extra-components#51]
In my table I have a column active/inactive. With the rowStyleClassDataProvider I add a greyed-out-style class depending on active=0 or 1. This works fine on the first page of data. When scrolling through the records all is well. 

On consecutive pages however, inactive lines are initially greyed-out but after scrolling through them they are not greyed-out any longer.

Return to page1 of the data and all is well again. Ring any bells?

**Comment by costescuandrei** [comment]
No bells... But we have to check this/fix it.
https://support.servoy.com/browse/SVY-12850
