### ISSUE TITLE
Table Component scrollbar issues Firefox

### ISSUE THREAD

**Issue by mboegem** [Servoy/servoy-extra-components#56]
I've set responsiveDynamicHeight on the table.
Results for all browsers are correct, but Firefox (Win&Mac) keep showing a vertical scrollbar.
Seems like the correct height is off by 1 or 2px resulting in this scrollbar.

![table](https://user-images.githubusercontent.com/8728009/59969099-59e5ea00-9546-11e9-94a2-2913f003852b.png)
![properties](https://user-images.githubusercontent.com/8728009/59969100-5d797100-9546-11e9-988f-63f74bd376d6.png)

**Comment by mboegem** [comment]
Additional on the latest browser versions, but running on Windows 7 for example, rendering is completely different and scrollbars both horizontal and vertical appear.

**Comment by costescuandrei** [comment]
Created https://support.servoy.com/browse/SVY-14870 to see what's going on.

**Comment by lvostinar** [comment]
Issue is fixed now, see jira case above.
