### ISSUE TITLE
Warning "Same lib with lower version found"

### ISSUE THREAD

**Issue by wvitpr** [Servoy/servoy-extra-components#57]
Would it be possible to sync to libs please, to avoid getting this warning constantly.

WARN org.sablo.IndexPageEnhancer - same lib with lower version found: {"name":"bootstrap","mimetype":"text/javascript","version":"3.3.7","url":"bootstrapextracomponents/lib/js/bootstrap.min.js"} using lib: {"name":"bootstrap","mimetype":"text/javascript","version":"3.4.1","url":"servoyextra/lib/js/bootstrap.min.js"}
WARN org.sablo.IndexPageEnhancer - same lib with lower version found: {"name":"bootstrap","mimetype":"text/javascript","version":"3.3.7","url":"bootstrapextracomponents/lib/js/bootstrap.min.js"} using lib: {"name":"bootstrap","mimetype":"text/javascript","version":"3.4.1","url":"servoyextra/lib/js/bootstrap.min.js"}

**Comment by costescuandrei** [comment]
This should be fixed now; I see both use 3.4.1.
