### ISSUE TITLE
select2tokenizer selection using type ahead leaves unfinished text

### ISSUE THREAD

**Issue by iangus** [Servoy/servoy-extra-components#6]
After entering a selection using the type ahead the unfinished search text is left along with the added token.

**Comment by paronne** [comment]
I can't replicate this issue; would be possible for you to record a video for this issue; also, which property of the component are enabled from: selectOnClose, closeOnSelect , allowNewEntries ?

**Comment by iangus** [comment]
[Here](http://screencast.com/t/33KBqyJf) is an example.
selectOnClose = false
closeOnSelect = false
allowNewEntries = false

**Comment by paronne** [comment]
Thank you for the video; such behavior is an intented behavior of the component and of the used library select2; i have added a new component's property 'clearSearchTextOnSelect' which you can set to true to have the behavior you desire. The question i had is what should be shown in the list once a selection is made and the searchText has been cleared ? I believe that the dropdown list should load back all result, therefore after a selection a refresh the dropdown list to default. 
I have pushed this commit in the 'develop' branch; is it possible for you to checkout this branch and confirm that fits your requirements ?

**Comment by iangus** [comment]
Yes, this is the desired functionality. Thank you.

**Comment by iangus** [comment]
Sorry to reopen this, but I've noticed an issue with the behavior. Currently if clearSeachTextOnSelect is true and closeOnSelect is false the dropdown will refresh every time a selection is made. I think this should only be done when there is actually search text, so the on select method should check searchText before clearing and refreshing

**Comment by paronne** [comment]
Good catch.
