### ISSUE TITLE
treeview Awesome icon dataset format

### ISSUE THREAD

**Issue by juanetec** [Servoy/servoy-extra-components#64]
Hi, reading the treeview wiki  it permit to put awesome font as a icon, but I could not find the exactly way to do it.

This is the way that I try to do:
`var treeviewDataSet = databaseManager.createEmptyDataSet( 0,  ['id', 'pid', 'treeColumn', 'icon']);
treeviewDataSet.addRow([1,		null,	'Main group',	'fa fa-users']);`

I put the awesome font like the wiki say but it gave me that error:
`WARN com.servoy.j2db.util.Debug - Invalid media value received: fad fa-cogs, cannot resolve it.`

Please, what I am doing bad?

Un Saludo 

Juan Ramírez

**Comment by gboros** [comment]
hi,
you should use 'fa-icon' instead of 'icon' in the first row of the dataset

regards,
Gabi

**Comment by juanetec** [comment]
Hi Gabi,
I try to do what you are saying an it doesn't work.
What I am doing wrong??

`var treeviewDataSet = databaseManager.createEmptyDataSet( 0,  ['id', 'pid', 'treeColumn', 'fa-icon']);
	treeviewDataSet.addRow([1,		null,	'Main group',	'fa fa-users']);
	treeviewDataSet.addRow([2,		null,	'Second group',	'fa fa-users']);
	treeviewDataSet.addRow([3,		2,		'Subgroup',		'fa fa-users']);
	treeviewDataSet.addRow([4,		3,		'Mark',			'fa fa-users']);
	treeviewDataSet.addRow([5,		3,		'George',		'fa fa-users']);
	elements.mytree.setDataSet(treeviewDataSet);`

Un Saludo

Jua nRamírez

**Comment by gboros** [comment]
do you have the "Font Awesome" service added to the solution (from Servoy Package Manager)?

**Comment by juanetec** [comment]
Yes, of course.

**Comment by gboros** [comment]
then it should just work; can you drop a sample here to have a look?

**Comment by juanetec** [comment]
There is an example.

**Comment by gboros** [comment]
your sample code works fine for me, I did say to drop a sample so we are in the same context

**Comment by juanetec** [comment]
ok Thanks I will wait for it.
I don't need it know.

Un Saludo

Juan Ramírez
