### ISSUE TITLE
select2tokenizer minimum height is too large

### ISSUE THREAD

**Issue by iangus** [Servoy/servoy-extra-components#8]
In Servoy the minimum height for the select2tokenizer is 33 while the standard height for all other fields is 20. Scaling the component down further simply moves the dropdown into the component it doesn't change the size.

**Comment by paronne** [comment]
min-height has been removed, the component will show a scrollbar if content doesn't fit.
The content of the component doesn't scale with the dimensions of the field; therefore new css classes, which can be set in the styleClass property of the tokenizer, has been introduced to allow size-management of the field: select2-xs, select2-sm, select2-md, select2-lg.
For a tokenizer having 20px height select the styleClass select2-xs.
